# Generated by Django 4.2 on 2023-05-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Photo', verbose_name='Home main img')),
            ],
        ),
    ]
