# Generated by Django 4.2 on 2023-05-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mainimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeInfo',
        ),
        migrations.DeleteModel(
            name='MainImg',
        ),
        migrations.AddField(
            model_name='homereference',
            name='img',
            field=models.ImageField(default=1, upload_to='Photo', verbose_name='Home main img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homereference',
            name='info',
            field=models.TextField(default=0, max_length=1000, verbose_name='Home info'),
            preserve_default=False,
        ),
    ]
