# Generated by Django 4.2 on 2023-05-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutt', models.TextField(max_length=200, verbose_name='About')),
                ('best_food', models.TextField(max_length=1500, verbose_name='Best food')),
                ('img', models.ImageField(upload_to='Photo', verbose_name='Image')),
            ],
        ),
    ]
