# Generated by Django 4.2 on 2023-05-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Photo', verbose_name='Image')),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('food', models.TextField(max_length=1500, verbose_name='food')),
                ('date', models.CharField(max_length=30, verbose_name='Date')),
            ],
        ),
    ]
