# Generated by Django 4.2 on 2023-05-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='User name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.TextField(max_length=20, verbose_name='Phone number')),
                ('review', models.TextField(max_length=400, verbose_name='Review')),
            ],
        ),
    ]
